# ---------------------------------------------------------------------------------------------------------------------
# Scan Config
# ---------------------------------------------------------------------------------------------------------------------
download-external-modules: true
evaluate-variables: true
skip-framework: secrets
skip-path:
- examples/


# ---------------------------------------------------------------------------------------------------------------------
# Output Format
# ---------------------------------------------------------------------------------------------------------------------
compact: true
skip-fixes: true
quiet: true


# ---------------------------------------------------------------------------------------------------------------------
# Skip Non-security checks to produce high value, low noise findings
# Skip checks that are not directly security risks like...
# * S3 bucket versioning
# * Best practices
# * High availibility
# * Tagging
# * Logging
# * Backups
# ---------------------------------------------------------------------------------------------------------------------

skip-check:
  # Category: AWS, Low security risks
  - CKV_AWS_21 # Ensure the S3 bucket has versioning enabled
  - CKV_AWS_23 # Ensure every security groups rule has a description
  - CKV_AWS_34 # Ensure cloudfront distribution ViewerProtocolPolicy is set to HTTPS
  - CKV_AWS_40 # Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.)
  - CKV_AWS_51 # Ensure ECR Image Tags are immutable
  - CKV_AWS_55 # Ensure S3 bucket has ignore public ACLs enabled
  - CKV_AWS_56 # Ensure S3 bucket has 'restrict_public_bucket' enabled
  - CKV_AWS_93 # Ensure S3 bucket policy does not lockout all but root user. (Prevent lockouts needing root account fixes)
  - CKV_AWS_115 # Ensure that AWS Lambda function is configured for function-level concurrent execution limit
  - CKV_AWS_116 # Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)
  - CKV_AWS_120 # Ensure API Gateway caching is enabled
  - CKV_AWS_123 # Ensure that VPC Endpoint Service is configured for Manual Acceptance
  - CKV_AWS_124 # Ensure that CloudFormation stacks are sending event notifications to an SNS topic
  - CKV_AWS_128 # Ensure that an Amazon RDS Clusters have AWS Identity and Access Management (IAM) authentication enabled
  - CKV_AWS_135 # Ensure that EC2 is EBS optimized
  - CKV_AWS_138 # Ensure that ELB is cross-zone-load-balancing enabled
  - CKV_AWS_139 # Ensure that RDS clusters have deletion protection enabled
  - CKV_AWS_143 # Ensure that S3 bucket has lock configuration enabled by default
  - CKV_AWS_144 # Ensure that S3 bucket has cross-region replication enabled
  - CKV_AWS_150 # Ensure that Load Balancer has deletion protection enabled
  - CKV_AWS_152 # Ensure that Load Balancer (Network/Gateway) has cross-zone load balancing enabled
  - CKV_AWS_157 # Ensure that RDS instances have Multi-AZ enabled
  - CKV_AWS_161 # Ensure RDS database has IAM authentication enabled
  - CKV_AWS_162 # Ensure RDS cluster has IAM authentication enabled
  - CKV_AWS_163 # Ensure ECR image scanning on push is enabled
  - CKV_AWS_165 # Ensure Dynamodb point in time recovery (backup) is enabled for global tables
  - CKV_AWS_172 # Ensure QLDB ledger has deletion protection enabled
  - CKV2_AWS_1 # Ensure that all NACL are attached to subnets
  - CKV2_AWS_1 # Ensure that all NACL are attached to subnets
  - CKV2_AWS_5 # Ensure that Security Groups are attached to an other resource
  - CKV2_AWS_12 # Ensure the default security group of every VPC restricts all traffic
  - CKV2_AWS_14 # Ensure that IAM groups includes at least one IAM user
  - CKV2_AWS_15 # Ensure that auto Scaling groups that are associated with a load balancer, are using Elastic Load Balancing health checks.
  - CKV2_AWS_16 # Ensure that Auto Scaling is enabled on your DynamoDB tables
  - CKV2_AWS_19 # Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances
  - CKV2_AWS_21 # Ensure that all IAM users are members of at least one IAM group.
  - CKV2_AWS_22 # Ensure an IAM User does not have access to the console

  # Category: AWS, Tagging
  - CKV_AWS_153 # Autoscaling groups should supply tags to launch configurations

  # Category: AWS, Logging
  - CKV_AWS_71 # Ensure Redshift Cluster logging is enabled
  - CKV_AWS_75 # Ensure Global Accelerator accelerator has flow logs enabled
  - CKV_AWS_76 # Ensure API Gateway has Access Logging enabled
  - CKV_AWS_80 # Ensure MSK Cluster logging is enabled
  - CKV_AWS_84 # Ensure Elasticsearch Domain Logging is enabled
  - CKV_AWS_86 # Ensure Cloudfront distribution has Access Logging enabled
  - CKV_AWS_91 # Ensure the ELBv2 (Application/Network) has access logging enabled
  - CKV_AWS_92 # Ensure the ELB has access logging enabled
  - CKV_AWS_101 # Ensure Neptune logging is enabled
  - CKV_AWS_104 # Ensure DocDB has audit logs enabled
  - CKV_AWS_18 # S3: Ensure the S3 bucket has access logging enabled
  - CKV_AWS_37 # Ensure Amazon EKS control plane logging enabled for all log types
  - CKV_AWS_48 # Ensure MQ Broker logging is enabled
  - CKV_AWS_50 # X-ray tracing is enabled for Lambda
  - CKV_AWS_65 # Ensure container insights are enabled on ECS cluster
  - CKV_AWS_73 # Ensure API Gateway has X-Ray Tracing enabled
  - CKV_AWS_85 # Ensure DocDB Logging is enabled
  - CKV_AWS_118 # Ensure that enhanced monitoring is enabled for Amazon RDS instances
  - CKV_AWS_118 # Ensure that enhanced monitoring is enabled for Amazon RDS instances
  - CKV_AWS_126 # Ensure that detailed monitoring is enabled for EC2 instances
  - CKV_AWS_129 # Ensure that respective logs of Amazon Relational Database Service (Amazon RDS) are enabled
  - CKV2_AWS_4 # Ensure API Gateway stage have logging level defined as appropriate
  - CKV2_AWS_4 # Ensure API Gateway stage have logging level defined as appropriate
  - CKV2_AWS_11 # Ensure VPC flow logging is enabled in all VPCs, not enforced due to cost.
  - CKV2_AWS_27 # Ensure Postgres RDS as aws_rds_cluster has Query Logging enabled
  - CKV2_AWS_27 # Ensure Postgres RDS as aws_rds_cluster has Query Logging enabled
  - CKV2_AWS_30 # Ensure Postgres RDS as aws_db_instance has Query Logging enabled
  - CKV2_AWS_30 # Ensure Postgres RDS as aws_db_instance has Query Logging enabled

  # Category: AWS, Backups
  - CKV2_AWS_8 # Ensure that RDS clusters has backup plan of AWS Backup
  - CKV2_AWS_9 # Ensure that EBS are added in the backup plans of AWS Backup
  - CKV2_AWS_13 # Ensure that Redshift clusters has backup plan of AWS Backup
  - CKV2_AWS_18 # Ensure that Elastic File System (Amazon EFS) file systems are added in the backup plans of AWS Backup
  - CKV_AWS_28 # Ensure Dynamodb point in time recovery (backup) is enabled
  - CKV_AWS_133 # Ensure that RDS instances has backup policy
  - CKV_AWS_134 # Ensure that Amazon ElastiCache Redis clusters have automatic backup turned on

  # Category: K8S, Low security risks 
  - CKV_K8S_8 # Liveness Probe Should be Configured
  - CKV_K8S_9 # Readiness Probe Should be Configured
  - CKV_K8S_10 # CPU Requests should be set
  - CKV_K8S_11 # CPU Limits should be set
  - CKV_K8S_12 # Memory requests should be set
  - CKV_K8S_13 # Memory limits should be set
  - CKV_K8S_14 # Image Tag should be fixed - not latest or blank
  - CKV_K8S_15 # Image Pull Policy should be Always
  - CKV_K8S_31 # Ensure that the seccomp profile is set to docker/default or runtime/default, alpha feature, hence disabled
  - CKV_K8S_32 # Ensure that the seccomp profile is set to docker/default or runtime/default, alpha feature, hence disabled
  - CKV_K8S_43 # Image should use digest

  # Category: Docker, Low security risks
  - CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_7 # Ensure the base image uses a non latest version tag

  # Added by Vespa team
  - CKV_AWS_231 # Ensure no NACL allow ingress from 0.0.0.0:0 to port 3389 - No RDP enabled
  - CKV2_AWS_38 # Ensure Domain Name System Security Extensions (DNSSEC) signing is enabled for Amazon Route 53 public hosted zones - Consider configuring later
  - CKV2_AWS_39 # Ensure Domain Name System (DNS) query logging is enabled for Amazon Route 53 hosted zones - Too much logging
  - CKV2_AWS_62 # Ensure S3 buckets should have event notifications enabled - Too much logging
